services:
  support:
    image: omnicrm-support:latest
    container_name: omnicrm-support
    networks:
      - n8n-compose_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.support.rule=Host(`support.zubenko.de`)
      - traefik.http.routers.support.entrypoints=web,websecure
      - traefik.http.routers.support.tls=true
      - traefik.http.services.support.loadbalancer.server.port=80
    restart: unless-stopped

networks:
  n8n-compose_default:
    external: true
